Adding concurrent envs
HorizenOfficial/rpc-tests pull request #18
Opened 2023-09-28 00:53 UTC by somethingih

2023-10-03 23:15 UTC, somethingih commented
@rabyyuson This should be taken care of. I have removed the the debug test case and the Transaction tests from EON

2023-10-05 12:05 UTC, rushby requested changes
What is the purpose of the tags?  They are not being used and should be removed, unless I am missing something.

The test pattern filtering you have added is done by directory.

{ tags: 'debug'})

2023-10-11 16:15 UTC, rushby approved these changes

2023-10-11 17:00 UTC, rabyyuson approved these changes
just need to resolve the conflicts in the **travis.yml** file

2023-10-11 17:30 UTC, merged